require("dotenv").config();

function getBeerSeed() {
    const beers = [
        {
          "id": 1,
          "name": "Head Hunter",
          "description": "Head Hunter is an award-winning, aggressively dry-hopped, West Coast-Style IPA with a huge hop display of pine, grapefruit, citrus and pineapple. A punch-you-in-the-mouth brew for those who truly love their hops!",
          "image": "/images/fh_website_2021_canglassphoto_headhunter_sz.png",
          "background": "/images/fh3299headhunter_beerpage_watercolor_bgindd-crop-u77158.jpg",
          "abv": 7.5,
          "brewery": "Fat head's",
          "style": "IPA",
          "price": 11.99
        },
        {
          "id": 2,
          "name": "Bumble Berry",
          "description": "Brewed with fresh harvested spring honey and infused with fresh blueberries. A light, refreshing ale with a nice blueberry aroma, crackery malt flavors, a hint of sweetness and a refreshing blueberry finish.",
          "image": "/images/fh_web_beerpage_feb2020_canglassphoto_bumbleberry-crop-u89116.png",
          "background": "/images/beerpage_watercolorback_bumble-crop-u77357.jpg",
          "abv": 5.3,
          "brewery": "Fat Head's",
          "style": "Blueberry Ale",
          "price": 10.99
        },
        {
          "id": 3,
          "name": "Sunshine Daydream",
          "description": "Award-Winning Session IPA with big hop aromas, flavors of citrus, peach, orange and tropical fruit with a nice light malt backbone. This is a very drinkable session ale. (Our fans call it an obsession.) Peace, Love & Hoppiness!",
          "image": "/images/fh_web_beerpage_feb2020_canglassphoto_sunshinedaydream-crop-u89737.png",
          "background": "/images/beerpage_watercolorback_sunshine-crop-u77256.jpg",
          "abv": 4.9,
          "brewery": "Fat Head's",
          "style": "IPA",
          "price": 12.99
        },
        {
          "id": 4,
          "name": "Goggle Fogger",
          "description": "When this brew first came out of the tanks our brewer took a sip. Then downed some more. He put on his glasses, tilted his head and said Damn, that's a Goggle Fogger! The Hefe prefix means with yeast which gives this unfiltered wheat beer a somewhat cloudy or foggy appearance. Light aromas of wheat, bubblegum, clove and spice.",
          "image": "/images/fh_website_2019_canandglassphoto_goggle-crop-u902601.png",
          "background": "/images/goggle_watercolorback_2019-crop-u9026066.jpg",
          "abv": 5.4,
          "brewery": "Fat Head's",
          "style": "German Style hefe-weizen",
          "price": 9.99
        },
        {
          "id": 5,
          "name": "Strange Magic",
          "description": "The magic is in our masterful combination of hops that create this ridiculously good India Pale Ale. The strange thing is how we get as much of it as we do into cans before we drink all of it ourselves.",
          "image": "/images/fh_website_2019_beerandglassphoto_strange-crop-u1019524.png",
          "background": "/images/strange_watercolorback_2019-crop-u1019527.jpg",
          "abv": 6.5,
          "brewery": "Fat Head's",
          "style": "IPA",
          "price": 11.99
        },
        {
          "id": 6,
          "name": "Groovy Juicy",
          "description": "The magic is in our masterful combination of hops that create this ridiculously good India Pale Ale. The strange thing is how we get as much of it as we do into cans before we drink all of it ourselves.",
          "image": "/images/fh_website_2020_canglassphoto_juicy_sz-crop-u1217654.png",
          "background": "/images/groovyjuice_beerpage_watercolorback-crop-u12176645.jpg",
          "abv": 7.1,
          "brewery": "Fat Head's",
          "style": "Hazy IPA",
          "price": 10.99
        },
        {
          "id": 7,
          "name": "Fresh Hop Freddy",
          "description": "Juicy tropical notes of guava, passionfruit, pineapple, and melon are blended with bright citrus notes of lime, and grapefruit. The Fresh Frozen hops create a pretty spectacular hop flavor and aroma in this year-round fresh AF IPA.",
          "image": "/images/freshhopfreddy_canglass-crop-u1367075.png",
          "background": "/images/freddy_webpage_watercolor-crop-u13670856.jpg",
          "abv": 6,
          "brewery": "Fat Head's",
          "style": "IPA",
          "price": 12.99
        },
        {
          "id": 8,
          "name": "Lime Feelin' Good",
          "description": "This lightly hopped lager is a real easy drinker. Fermented with Mexican-style lager yeast for authenticity. Just garnish it with a juicy wedge of lime... feels like the right thing to do!",
          "image": "/images/limefeelincan_glass.png",
          "background": "/images/limefeelingood_webpage-crop-u13883996.jpg",
          "abv": 4.9,
          "brewery": "Fat Head's",
          "style": "Mexican Lager",
          "price": 8.99
        },
        {
          "id": 9,
          "name": "G'Suffa!",
          "description": "Imported German malts give this modern Festbier a subtle sweetness. Lighter in body than a Marzen and deep gold in color with aromas of toasted grains. Crisp, crackery malt flavor balanced by German noble hop flavor and aroma. Smooth and highly drinkable.",
          "image": "/images/fh_website_canglass_gsuffa_june2020.png",
          "background": "/images/beerpage_watercolorback_gsuffa-crop-u162695.jpg",
          "abv": 5.7,
          "brewery": "Fat Head's",
          "style": "Oktoberfest Lager",
          "price": 7.99
        },
        {
          "id": 10,
          "name": "Spooky Tooth",
          "description": "Rich amber color with aroma of sweet pumpkin pie and savory spices. Creamy mouthfeel with flavors of pumpkin followed by sweet malt, pie crust, spice, hints of brown sugar and a clean finish.",
          "image": "/images/fh_website_canglass_spooky_june2020.png",
          "background": "/images/beerpage_watercolorback_spooky-crop-u162794.jpg",
          "abv": 9,
          "brewery": "Fat Head's",
          "style": "Pumpkin Ale",
          "price": 13.79
        },
        {
          "id": 11,
          "name": "All Day IPA",
          "description": "The beer you’ve been waiting for. Keeps your taste satisfied while keeping your senses sharp. An all-day IPA naturally brewed with a complex array of malts, grains and hops. Balanced for optimal aromatics and a clean finish. The perfect reward for an honest day’s work and the ultimate companion to celebrate life’s simple pleasures.",
          "image": "https://foundersbrewing.com/wp-content/uploads/2017/08/2020_all_day_ipa.png",
          "background": "https://foundersbrewing.com/wp-content/uploads/2017/08/ALL_DAY_IPA__subpage_header.jpg",
          "abv": 4.7,
          "brewery": "Founders Brewing CO.",
          "style": "IPA",
          "price": 10.49
        },
        {
          "id": 12,
          "name": "All Day Haze",
          "description": "We often have our head in the clouds – and once again we came back down with an exciting idea: let’s take the low ABV of All Day IPA and bring it to a hazy! That’s just what we did with All Day Haze Hazy IPA. A substantial amount of oats and wheat lend a whimsical fogginess, while Citra, Simcoe and Amarillo hops create an explosion of aroma.  A sessionable, cloudy treat that can be enjoyed in any weather, hazy or otherwise.",
          "image": "https://foundersbrewing.com/wp-content/uploads/2021/11/2021_All_Day_Haze_lineup-e1637082702467.png",
          "background": "https://foundersbrewing.com/wp-content/uploads/2021/11/All_Day_Haze_HeroBanner-scaled.jpg",
          "abv": 4.9,
          "brewery": "Founders Brewing CO.",
          "style": "Hazy IPA",
          "price": 8.50
        },
        {
          "id": 13,
          "name": "All Day Vacay",
          "description": "You’re going to need a bigger suitcase – All Day Vacay has arrived. Take a well-earned respite from the mundane and let this session wheat ale whisk you away with its slight, summery sweetness – complemented by delicate notes of citrus. Whether it’s a staycay or vacay, it’s the perfect companion for any type of adventure.",
          "image": "https://foundersbrewing.com/wp-content/uploads/2021/01/2020_all_day_vacay_lineup.png",
          "background": "https://foundersbrewing.com/wp-content/uploads/2021/01/all_day_vacay_HeroBanner-01.png",
          "abv": 4.6,
          "brewery": "Founders Brewing CO.",
          "style": "Wheat Ale",
          "price": 18.99
        },
        {
          "id": 14,
          "name": "CENTENNIAL IPA",
          "description": "Get ready to bask in the glory of the frothy head’s floral bouquet. Relish the citrus accents from the abundance of dry hopping. This one’s sweet, yet balanced. Malty undertones shake hands with the hop character for a finish that never turns too bitter.",
          "image": "https://foundersbrewing.com/wp-content/uploads/2017/08/2020_centennial_lineup.png",
          "background": "https://foundersbrewing.com/wp-content/uploads/2017/08/CentennialIPA_HeroBanner-2.jpg",
          "abv": 7.2,
          "brewery": "Founders Brewing CO.",
          "style": "IPA",
          "price": 10.49
        },
        {
          "id": 15,
          "name": "Two Hearted Ale",
          "description": "Brewed with 100% Centennial hops from the Pacific Northwest and named after the Two Hearted River in Michigan’s Upper Peninsula, our American IPA is bursting with hop aromas ranging from pine to grapefruit from massive hop additions in both the kettle and the fermenter.",
          "image": "/images/TwoHearted_736px-2.png",
          "background": "/images/Two_Hearted_Fish_back.jpeg",
          "abv": 7,
          "brewery": "BELL's",
          "style": "American IPA",
          "price": 19.99
        },
        {
          "id": 16,
          "name": "Amber Ale",
          "description": "Features both toasted and sweet caramel notes from carefully selected malts, balanced with herbal and citrus hop aromas. Capped by a clean bitterness,",
          "image": "/images/AmberAle_736px-1.png",
          "background": "/images/AmberBackground.jpeg",
          "abv": 5.8,
          "brewery": "BELL's",
          "style": "Amber Ale",
          "price": 10.99
        },
        {
          "id": 17,
          "name": "OFFICIAL HAZY IPA",
          "description": "Two of our favorite ingredients come together in the brewhouse; pungent American hops and delicious wheat malt. This Hazy IPA is double dry-hopped (a combination of Mosaic, Citra, Azacca, Amarillo, and El Dorado hops) resulting in complex peach, stone fruit, and tropical notes with a dry finish and balanced bitterness.",
          "image": "/images/Official-BeerRender-736px.png",
          "background": "/images/OfficialBackground.jpeg",
          "abv": 6.4,
          "brewery": "BELL's",
          "style": "Hazy IPA",
          "price": 10.99
        },
        {
          "id": 18,
          "name": "Losun",
          "description": "Bright and smooth with subtle citrus hop aromas, this easy-drinking wheat ale is only 110 calories and sessionable any time of the day.",
          "image": "/images/LoSun-Render.png",
          "background": "/images/LoSun-Hero-Textjpg.jpg",
          "abv": 4,
          "brewery": "BELL's",
          "style": "Wheat Ale",
          "price": 10.99
        },
        {
          "id": 19,
          "name": "Oberon Ale",
          "description": "Oberon is a wheat ale fermented with our signature house ale yeast, mixing a spicy hop character with mildly fruity aromas. The addition of wheat malt lends a smooth mouthfeel, making it a classic summer beer.",
          "image": "/images/MicrosoftTeams-image-102.png",
          "background": "/images/MicrosoftTeams-image-103.png",
          "abv": 5.8,
          "brewery": "BELL's",
          "style": "American Wheat Ale",
          "price": 12.50
        },
        {
          "id": 20,
          "name": "Octoberfest Beer",
          "description": "Crafted as a flavorful session beer and perfect for autumn, Octoberfest spends a full six weeks fermenting. Perfect for a week-long wedding celebration in Germany or the start of the Michigan autumn",
          "image": "/images/Octoberfest-Render.png",
          "background": "/images/Octoberfest-Hero-Text.jpg",
          "abv": 5.5,
          "brewery": "BELL's",
          "style": "Oktoberfest Lager",
          "price": 13.75
        },
        {
          "id": 21,
          "name": "GINGER LIME FLAMINGO FRUIT FIGHT",
          "description": "Driven by prominent notes of ginger and tart lime, this sessionable Fruit Fight has an almost cocktail-like character.",
          "image": "/images/Ginger-Lime-FFF-Render.png",
          "background": "/images/Ginger-Lime-FFF-Hero.jpg",
          "abv": 4,
          "brewery": "BELL's",
          "style": "Ginger Lime Ale",
          "price": 12.99
        },
        {
          "id": 22,
          "name": "Double Two Hearted Ale",
          "description": "With two and a half times the amount of Centennial hops, Double Two Hearted has intense pine and citrus notes, a resinous hop aroma, and a rich malt character.",
          "image": "/images/Double-Two-Hearted-Render.png",
          "background": "/images/DTH-Hero.jpg",
          "abv": 11,
          "brewery": "BELL's",
          "style": "Double American IPA",
          "price": 19.99
        },
        {
          "id": 23,
          "name": "POMEGRANATE FLAMINGO FRUIT FIGHT",
          "description": "This tart fruit ale goes straight for the taste buds, with a dry finish and fruity notes.",
          "image": "",
          "background": "",
          "abv": 4.5,
          "brewery": "BELL's",
          "style": "Sour Ale",
          "price": 12.99
        },
        {
          "id": 24,
          "name": "THIRD COAST OLD ALE",
          "description": "A mixture of burnt caramel and other earthy malt flavors, with enough hop presence to prevent a sense of sweetness. Sharply bitter when first packaged, this hop aspect will fold into the malt character over time and find balance.",
          "image": "/images/History_ThirdCoastOldAle.png",
          "background": "/images/TCOA-Hero-.jpg",
          "abv": 10.2,
          "brewery": "BELL's",
          "style": "American Barley Wine Ale",
          "price": 17.99
        },
        {
          "id": 25,
          "name": "TEQUILA BARREL-AGED FLAMINGO FRUIT FIGHT",
          "description": "Everything you love about our original Flamingo Fruit Fight - passionfruit and lime zest - but aged in Tequila barrels, taking this tart ale to new heights.",
          "image": "/images/Tequila-BA-Flamingo-Render.png",
          "background": "/images/Tequila-BA-Flamingo-Fruit-Fight_HERO.jpg",
          "abv": 6,
          "brewery": "BELL's",
          "style": "Lime Tart Ale",
          "price": 14.49
        },
        {
          "id": 26,
          "name": "Chillwave",
          "description": "Inspired by the North Coast's dedicated (and sometimes chilly) surf community, our fully stoked Imperial IPA will melt the ice in your beard and never lose its balance.",
          "image": "/images/16oz_chillwave-1c-final.png",
          "background": "/images/chillwave-header-500 (1).jpg",
          "abv": 9,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Imperial IPA",
          "price": 16.75
        },
        {
          "id": 27,
          "name": "Burning River",
          "description": "Greetings from Cleveland! Where an infamous river fire rekindled appreciation for our region’s natural resources (like the malt and hops illuminating this Pale Ale).",
          "image": "/images/burning-river-rendering_0.png",
          "background": "/images/burning-river-header-500 (1).jpg",
          "abv": 6,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Pale Ale",
          "price": 10.99
        },
        {
          "id": 28,
          "name": "Christmas Ale",
          "description": "Do not open ‘til Christmas? Whoever coined that phrase obviously hasn’t tasted Christmas Ale’s fresh honey, cinnamon, and ginger flavors.",
          "image": "/images/christmas-ale-rendering.png",
          "background": "/images/christmasale2020_final_500.jpg",
          "abv": 7.5,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Ale",
          "price" : 11.99
        },
        {
          "id": 29,
          "name": "COMMODORE PERRY",
          "description": "What’s this? A British-style IPA named after the man who defeated His Majesty’s Royal Navy in the War of 1812? Consider this a bold, hoppy (and mildly ironic) plunder of war.",
          "image": "/images/commodore-render.png",
          "background": "/images/commodore-header-500.jpg",
          "abv": 7.7,
          "brewery": "Great Lakes Brewing Co.",
          "style": "IPA",
          "price": 10.99
        },
        {
          "id": 30,
          "name": "CONWAY'S IRISH ALE",
          "description": "A pint for Pa Conway! Our co-owners’ grandfather and policeman who’d likely uphold that an Irish Ale with full-bodied caramel malt flavors is just the ticket.",
          "image": "/images/commodore-rendering_1.png",
          "background": "/images/conways-header-500.jpg",
          "abv": 6.3,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Irish Ale",
          "price": 16.99 
        },
        {
          "id": 31,
          "name": "CRUSHWORTHY",
          "description": "Do you believe in love at first sip? With a lightly filtered body and a sweet kiss of orange, it's more than a crush. It's your new main squeeze. 105 Calories. 4.0% ABV.",
          "image": "/images/crushworthy-rendering.png",
          "background": "/images/crushworthy-header-500.jpg",
          "abv": 4,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Citrus Wheat Ale",
          "price": 11.99 
        },
        {
          "id": 32,
          "name": "DANK DEMON",
          "description": "Leafy layers of heady hop aromas lurk in every wicked whiff of Dank Demon’s hauntingly full-bodied brew.",
          "image": "/images/dank-demon-rendering.png",
          "background": "/images/dank-demon-header-500.jpg",
          "abv": 8,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Imperial IPA",
          "price": 11.99
        },
        {
          "id": 33,
          "name": "DORTMUNDER GOLD",
          "description": "A classic award-winning balance of sweet malt and dry hop flavors, proudly waving the flag for Cleveland and refreshing beer drinkers everywhere since 1988.",
          "image": "/images/dort-beer-page-2.png",
          "background": "/images/dortmundergold_final_500.jpg",
          "abv": 5.8,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Lager",
          "price": 10.99  
        },
        {
          "id": 34,
          "name": "ELIOT NESS",
          "description": "Admittedly, it’s a bit of a paradox to name our Amber Lager for history’s most famous agent of prohibition. But it’s a smooth, malty (and dare we say, arresting?) paradox.",
          "image": "/images/ness-rendering.png",
          "background": "/images/eliot-ness-header-500.jpg",
          "abv": 6.1,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Amber Lager",
          "price": 10.99  
        },
        {
          "id": 35,
          "name": "EDMUND FITZGERALD",
          "description": "Robust and complex, our Porter is a bittersweet tribute to the legendary freighter’s fallen crew—taken too soon when the gales of November came early.",
          "image": "/images/fitz-rendering.png",
          "background": "public/images/fitz-header-500.jpg",
          "abv": 6,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Porter",
          "price": 10.99
        },
        {
          "id": 36,
          "name": "GREAT LAKES IPA",
          "description": "With a breezy, aromatic hop blend and clean malt flavor, our lightly filtered American IPA is as bright, bracing, and inviting as the beautiful lakes we call home.",
          "image": "/images/glipa-rendering.png",
          "background": "/images/glipa-header-500.jpg",
          "abv": 6.5,
          "brewery": "Great Lakes Brewing Co.",
          "style": "American IPA",
          "price": 10.99
        },
        {
          "id": 37,
          "name": "HAZECRAFT",
          "description": "3, 2, 1... we have haze! A cloudy cosmos of Azacca, Lemondrop, and Simcoe hops awaits exploration.",
          "image": "/images/hazecraft-rendering.png",
          "background": "/images/hazecraft-header-500.jpg",
          "abv": 6.7,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Hazy IPA",
          "price": 17.99 
        },
        {
          "id": 38,
          "name": "LEMON HEFEWEIZEN",
          "description": "Squeeze into your snazziest swimwear and float away with this frothy, zesty cooler companion brewed with enough lemon purée to last a long weekend.",
          "image": "/images/lemon-hefe-rendering.png",
          "background": "/images/hefe-header-resize.jpg",
          "abv": 5.1,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Lemon Ale",
          "price": 15.98
        },
        {
          "id": 39,
          "name": "LAKE ERIE MONSTER",
          "description": "Issue a small craft advisory: this South Bay Bessie-inspired brew launches an intense hop attack amid torrid tropical fruit flavors.",
          "image": "/images/lem-rendering.png",
          "background": "/images/lem-header-500.jpg",
          "abv": 9.5,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Imerial IPA",
          "price": 13.99
        },
        {
          "id": 40,
          "name": "MEXICAN LAGER",
          "description": "Find a sunny spot and lounge awhile with this golden Mexican-Style Lager, brewed with real lime peel and purée and flaked corn for a crisp and refreshing getaway.",
          "image": "/images/mexican-lager-rendering.png",
          "background": "/images/mexican-lager-header-500.jpg",
          "abv": 5.4,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Lime Lager",
          "price": 10.99
        },
        {
          "id": 41,
          "name": "NOSFERATU",
          "description": "Don’t be afraid of things that go hop in the night! Rich roasted malt flavors haunt the shadows of our Imperial Red IPA's bitter teeth.",
          "image": "/images/ness-rendering.png",
          "background": "/images/nosferatu-header-500.jpg",
          "abv": 8,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Imerial Red IPA",
          "price": 13.99
        },
        {
          "id": 42,
          "name": "OHIO CITY OATMEAL STOUT",
          "description": "Dark and roasty yet light and smooth as a fresh coat of snow, our Oatmeal Stout will kick your cabin fever and inspire you to toss another log on the fire.",
          "image": "/images/ohio-city-oatmeal-stout.png",
          "background": "/images/ohio-city-oatmeal-header-500.jpg",
          "abv": 5.4,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Oatmeal Stout",
          "price": 11.99 
        },
        {
          "id": 43,
          "name": "OKTOBERFEST",
          "description": "Prost! Our take on this classic German style is a real malt party, packed with toasty autumnal flavors perfect for hearty hoisting.",
          "image": "/images/oktoberfest-rendering.png",
          "background": "/images/okto-header-500.jpg",
          "abv": 6.5,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Marzen Lager",
          "price": 9.99 
        },
        {
          "id": 44,
          "name": "RALLY DRUM",
          "description": "For day games and night games, from the box to the bleachers, Rally Drum delivers with a clean-fielding golden malt body and a pure swing of fresh hop aromas. It’s the ultimate utility player.",
          "image": "/images/rally-drum-rendering.png",
          "background": "/images/rally-drum-header-500.jpg",
          "abv": 4.2,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Lager",
          "price": 9.99
        },
        {
          "id": 45,
          "name": "RUBY'S REVENGE",
          "description": "Fiercely fresh ruby red grapefruit tangles with tantalizing citrusy hop aromas to cultivate this biting Imperial IPA.",
          "image": "/images/ruby-revenge-can_0.png",
          "background": "/images/ruby-header-500.jpg",
          "abv": 8,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Imperial Grapefruit IPA",
          "price": 13.99
        },
        {
          "id": 46,
          "name": "TIDAL FURY",
          "description": "A tempest of tropical fruit aromas rushes from the cloudy depths in this Imperial Hazy IPA, brewed with an epic blast of Trident™ hops fit for a king.",
          "image": "/images/tidal-fury-rendering.png",
          "background": "/images/tidal-fury-header-500.jpg",
          "abv": 8,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Imerial Hazt IPA",
          "price": 13.99
        },
        {
          "id": 47,
          "name": "TROPICOASTAL",
          "description": "Make a splash landing into paradise and discover a golden oasis of tropical fruit notes. It’s a hoppy hideaway you’ll want to escape to again and again.",
          "image": "/images/tropicoastal-rendering.png",
          "background": "/images/tropicoastal-notype_final_500.jpg",
          "abv": 6,
          "brewery": "Great Lakes Brewing Co.",
          "style": "Tropical IPA",
          "price": 10.99
        },
        {
          "id": 48,
          "name": "Goose Island IPA",
          "description": "Goose Island’s flagship IPA is a six-time medal winner at the Great American Beer Festival. We’ve taken the traditional English Style and created our own fuller flavored IPA with bright citrus aromas and a bold hop finish. With hoppy, bold, and smooth flavor, Goose IPA is the perfect beer for hopheads and discovery drinkers alike.",
          "image": "/images/IPA_HERO_CAN.png",
          "background": "/images/ipa-big-label1.jpg",
          "abv": 5.9,
          "brewery": "Goose Island",
          "style": "IPA",
          "price": 9.99
        },
        {
          "id": 49,
          "name": "Matilda",
          "description": "Wild in character, a complex ale with dried fruit and clove aromas, and a satisfying dry finish. Inspired by great Trappist ales, our complex Belgian Style Pale Ale is fermented with the wild yeast Brettanomyces. Matilda pours a golden sunrise color with dried fruit and clove aromas, a spicy yeast flavor, and a satisfying dry finish.",
          "image": "/images/MatildaBottleFront.png",
          "background": "/images/GIBCo_TapSticker_Matilda3.png",
          "abv": 7,
          "brewery": "Goose Island",
          "style": "Belgian Style Ale",
          "price": 10.99
        },
        {
          "id": 50,
          "name": "Sofie",
          "description": "Our sparkling Belgian Style Farmhouse Ale is wine barrel-aged with an abundance of hand-zested orange peel. Spicy white pepper notes contrast the citrus tartness. The light, refreshing, creamy vanilla finish will excite those fond of Champagne. Originally brewed by Belgian farmers to attract the best farm hands, we were inspired to brew an exceptional ale as inviting as the original Belgian Farmhouse ales. Light and effervescent, we named it for our founder’s granddaughter Sofie.",
          "image": "/images/Sofie_rendering_2020.png",
          "background": "/images/Sofie_tapsticker_large_2020.jpg",
          "abv": 6.5,
          "brewery": "Goose Island",
          "style": "Belgian Ale",
          "price": 10.99
        },
        {
          "id": 51,
          "name": "Blackberry Smash",
          "description": "Our Blackberry Smash is our nod to a perfect cocktail sipper. Fruit-forward, fizzy, and easy to love. We paired blackberries with a slightly spicy, rye bourbon backbone and just enough mint to refresh and unwind on a long afternoon. No need to run out to buy any ingredients, just crack this cocktail open and enjoy straight from the can, in a glass, or over ice.",
          "image": "/images/BlkBSm2.png",
          "background": "/images/GI_BHC_BlackberrySmash_1750x1320.jpg",
          "abv": 9,
          "brewery": "Goose Island",
          "style": "Canned Cocktail",
          "price": 15.99
        },
        {
          "id": 52,
          "name": "Old Fashioned Highball",
          "description": "An Old Fashioned is a timeless whiskey cocktail. A true highball has a light, bubbly and refreshing character. We’ve brought the two together. Our take on a highball cocktail starts with the rye bourbon complexity, a touch of bitters, cane sugar, and a wisp of orange and cherry to round it out. So put the stir stick and peeler down, we already made this cocktail for you.",
          "image": "/images/Highball.png",
          "background": "/images/GI_BHC_OFHB_1750x1320.jpg",
          "abv": 9,
          "brewery": "Goose Island",
          "style": "Canned Cocktail",
          "price": 15.99
        },
        {
          "id": 53,
          "name": "Whiskey Sour",
          "description": "If there is one cocktail to ease your way into the world of bourbon, this might be it. Subtly sweet, tart, and spicy, yet hardly shy. Our riff on a whiskey sour pays tribute to that classic balance with rye bourbon, both lemon and lime, and a subtle maraschino cherry finish. No need to wait any longer than you need to for this cocktail, it’s ready to enjoy.",
          "image": "/images/WhskSr.png",
          "background": "/images/GI_BHC_WS_1750x1320.jpg",
          "abv": 9,
          "brewery": "Goose Island",
          "style": "Canned Cocktail",
          "price": 15.99
        },
        {
          "id": 54,
          "name": "Fat Tire",
          "description": "Fat Tire's unique flavor profile originates from 1930s Belgium. During this era, small breweries began offering easy-drinking beer crafted with signature Belgian yeast in order to satisfy the tastes of visiting British soldiers. Today, Fat Tire delivers drinkers everywhere a flavorful, balanced beer with a fresh herbal hop profile, fine malt presence and a touch of fruity yeast, making it a timeless beer with broad appeal.",
          "image": "/images/beer-fat-tire-amber-ale-desktop.png",
          "background": "/images/hero-fat-tire-tablet.jpg",
          "abv": 5.2,
          "brewery": "New Belgium",
          "style": "Amber Ale",
          "price": 11.99
        },
        {
          "id": 55,
          "name": "VooDoo Ranger IPA",
          "description": "Let’s just say Voodoo Ranger doesn’t take himself too seriously, and neither should you. The bottom line: if you’re looking for innovative IPAs that are hop forward, bold, and occasionally hazy, the Voodoo Ranger fam has your back.",
          "image": "/images/vripa_2021_globe_can_1440-right.png",
          "background": "/images/vripa-2021_tablet-100.jpg",
          "abv": 7,
          "brewery": "New Belgium",
          "style": "IPA",
          "price": 14.99
        },
        {
          "id": 56,
          "name": "VooDoo Ranger Imperial IPA",
          "description": "New Belgium Voodoo Ranger Imperial IPA is a rare blend of choice hops that creates an explosion of fresh-cut pine and citrus flavors for a complex, rich and delicious flavor.",
          "image": "/images/beer-vr-imperial-ipa-desktop (1).png",
          "background": "/images/vrimp_tablet-100.jpg",
          "abv": 9,
          "brewery": "New Belgium",
          "style": "Imperial IPA",
          "price": 16.99
        },
        {
          "id": 57,
          "name": "VooDoo Ranger Hazy IPA",
          "description": "Packed with bright tropical aromas and brilliant citrusy flavors, this unfiltered IPA wraps up with a pleasantly smooth finish.",
          "image": "/images/new-vrajh_pint_can_1440.png",
          "background": "/images/vrjh_tablet-100.jpg",
          "abv": 7.5,
          "brewery": "New Belgium",
          "style": "Hazy IPA",
          "price": 15.99
        }
    ]
    return beers;
}

module.exports = {getBeerSeed};